config/routes.rb
Rails.application.routes.draw do
 devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
 }

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
 }

  root 'homes#top'
  get '/about',to: 'homes#about'
  get '/search', to: 'searches#search'

  namespace :admins do
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  #customer

    resource :customer, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end

    resources :items, only: [:index, :show]

    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only: [:index, :show, :new, :create] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end

    resources :addresses, except: [:show, :new]

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
belongs_to :customer
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_admin

  def index
     @customers = Customer.page(params[:page]).reverse_order
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admins_customer_path(@customer), notice: '会員情報を更新しました。'
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number, :email, :is_deleted)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :authenticate_admin!
  
  def top
  end
  
  def index
    @items = Item.page(params[:page]).per(10)
  end
  
  def new
    @item = Item.new
    @genres = Genre.all
    
  end
  
  def show
    @item=Item.find(params[:id])
  end
  
  def edit
    @item=Item.find(params[:id])
    @genres = Genre.all
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to  admins_item_path(@item)
    else
      render :new
    end
 
  end
  
  def update
    @item=Item.find(params[:id])
    if @item.update(item_params)
    redirect_to admins_item_path(@item)
    else
    render:edit
    end
  end
  
   private
  
  def item_params
    params.require(:item).permit(:image,:name,:introduction,:price,:is_active,:genre_id)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_action :authenticate_admin!

  def index
   @orders = Order.page(params[:page]).per(10).reverse_order
  end
  
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    
    @order_details.each do |order_detail| 
      if order_detail.making_status == "製作不可"
        @condition_detail = order_detail.making_status == "製作不可"
      elsif @order.order_details.count == @order.order_details.where(making_status: 3).count
        @condition_detail = order_detail.making_status == "製作完了"
      end
    end
    
    if @order.status == "入金確認"
      @condition_order = @order.status == "入金確認"
    elsif @order.status == "製作中"
      @condition_order = @order.status == "製作中"
    elsif @order.status == "発送済み"
      @condition_order = @order.status == "発送済み"
      
    end
  end
  
  
  def update
    @order = Order.find(params[:id])
    @order_status = params[:order][:order_status].to_i
    @order.update(status: @order_status)
    
    if @order_status == 1
      @order.order_details.each do |order_detail|
        order_detail.update(making_status: 1)
      end
    end
    redirect_to   admins_order_path(@order)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end


  private
  def after_sign_in_path_for(resource)
     admins_orders_path
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/addresses/edit.html.erb
<div class="container">

  <div class="mt-5">
    <span class="fs-3  offset-md-1 bg-light font-monospace">配送先編集</span>
  </div>
  <%= form_with model: @address, local: true do |f| %>
    <div class="form-inline">
      <%= f.label :郵便番号（ハイフンなし）, class:"col-3 mt-5"%>
      <%= f.text_field :postcode, class:"col-3" %>
    </div>
    <div class="form-inline">
      <%= f.label :住所, class:"col-1 mt-3" %>
      <%= f.text_field :address, class:"offset-2 col-6" %>
    </div>
    <div class="form-inline">
      <%= f.label :宛名, class:"col-1 mt-3" %>
      <%= f.text_field :name, class:"offset-2 col-3" %>
    </div>
    <%= f.submit "変更内容を保存", class:"btn btn-success mt-5 offset-3" %>
  <% end %>

</div>

app/views/addresses/index.html.erb
<div class="container top-bg">
  <div class="mt-5">
    <span class="fs-3  offset-md-1 bg-light page-title">配送先登録/一覧</span>
  </div>
  <%= render "layouts/error", model: @address %>
  <%= form_with model: @address, local: true do |f| %>

    <div class="form-inline">
      <%= f.label :郵便番号（ハイフンなし）, class:"col-3 mt-5" %>
      <%= f.text_field :postcode, class:"col-3", placeholder:"0000000" %>
    </div>
  　<div class="form-inline">
      <%= f.label :住所, class:"col-1" %>
      <%= f.text_field :address, class:"offset-2 col-6", placeholder:"東京都渋谷区代々木神園町0-0" %>
    </div>
    <div class="form-inline">
      <%= f.label :宛名, class:"col-1 mt-4" %>
      <%= f.text_field :name, class:"offset-2 col-3", placeholder:"令和道子" %>
    </div>
    <%= f.submit "新規登録", class: "btn btn-success mt-5 offset-3" %>
  <% end %>

  <table class="table table-bordered mt-5 mb-5">
    <thead class="bg-light">
      <tr>
        <th>郵便番号</th>
        <th>住所</th>
        <th>宛名</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @addresses.each do |address| %>
        <tr>
          <td><%= address.postcode %></td>
          <td><%= address.address %></td>
          <td><%= address.name %></td>
          <td>
            <%= link_to "編集する", edit_address_path(address), class: "btn btn-success btn-sm offset-1" %>
            <%= link_to "削除する", address_path(address), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-danger btn-sm offset-1" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/homes/about.html.erb
<div class='about-visual px-5 px-sm-0'>

    <div class='col-md-11 offset-md-1'>

        <div class="d-flex align-items-center justify-content-center" style="height:300px;">

            <span class="about-text">
                 ながのCAKEは全国発送可能なケーキ屋さんです。<br>
                 お子様からお年寄りの方までお召しあがりいただけるよう、<br>
                 様々なバリエーションを用意しております。<br>
                 また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。<br>
                 ぜひご注文ください。
            </span>
        </div>

    </div>

</div>
<div class="row plugin">
  <div class="offset-sm-1 col-sm-3 mt-5">
     <a class="twitter-timeline" data-width="220" data-height="250" data-theme="light" href="https://twitter.com/CAKE_teamA?ref_src=twsrc%5Etfw">Tweets by CAKE_teamA</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>
  <div class="col-sm-2 mt-5">
    <iframe src="https://www.google.com/maps/d/u/0/embed?mid=1CCUCqr678RB_fZMavY9GAN8XgsWXhfjD" width="500" height="250"></iframe>
  </div>
 
</div>

app/views/homes/top.html.erb
<div class='top-bg px-5 px-sm-0'>



      <div class="top-message d-flex align-items-center justify-content-center" style="height:300px;">
        <div class="row">
          <div class="welcome-messge">
            Welcome To Nagano Cake！<br>
          </div>
          <div class="welcome-message-content">
            <% if current_customer.present? %>
              <%= current_customer.last_name %> 様<br>
            <% end %>
            洋菓子専門店ながのCakeにようこそ<br>
            会員でない方も商品の閲覧はできますが<br>
            購入には会員登録が必要になります<br>
          </div>
        </div>
      </div>

      <div class="text-center">
        <div class="item-link">
          <%= link_to items_path do %>
            <span class="items">Item</span>
          <% end %>
        </div>
        <span class="new-item">New Arrival</span>
      </div>

      <div class="item-image-slide">
        <% @items.each do |item| %>
          <div class="slide-item">
            <%= link_to item_path(item) do %>
              <%= attachment_image_tag item, :image, class:'sample-image'%>
            <% end %>
          </div>
        <% end %>
      </div>






  </div>
</div>